# Generated by Django 3.1.7 on 2021-03-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_title', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discovery', models.CharField(max_length=200, null=True)),
                ('proposal_shared', models.CharField(max_length=200, null=True)),
                ('negotiations', models.CharField(max_length=200, null=True)),
                ('associated_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunitiesmgt_app.account')),
            ],
        ),
    ]
